### ISSUE TITLE
Can you add sphinxagent to docker image?

### ISSUE THREAD

**Issue by NorthV** [macbre/docker-sphinxsearch#1]
https://tools.sphinxsearch.com/node/newmng

**Comment by macbre** [comment]
Download URL - https://tools.sphinxsearch.com/downloads/latest/

`sphinxmonitor` will be dockerized in a separate container to follow the "one process per container" rule.

From docs:

Adding a new managed node:
For Linux systems (debian and red-hat based):
A managed node allows full control of your Sphinx instance (the node) using the Tools website. For this to work an open port is required on your end.

Please note that you must have the SphinxQL port enabled in your config.

Default port used is `8082`. If you need to change it, you have edit both the `sphinxagent.json` configuration file of the Node Agent, as well as in Tools in the Edit page of the Node. If that's not an option for you, use the Monitor Agent.

To install the Node Agent, run the following command as root:

```
SPH_API_KEY=xxx bash -c "$(curl -s https://tools.sphinxsearch.com/downloads/latest/install-manager)"
```

Depending on distribution, the Agent expects sphinx.conf to be located at /etc/sphinxsearch/sphinx.conf ( debian-based distributions) or /etc/sphinx/sphinx.conf ( redhat-based distributions) and the Sphinx binaries at /usr/bin/. If you have custom settings, edit `/usr/local/sphinxagent/conf/sphinxagent.json`.

If everything is ok, start the Agent service:

```
service sphinxagent start
```

The monitoring data will start to appear in several minutes.

**Comment by macbre** [comment]
@NorthV - work will take place in https://github.com/macbre/docker-sphinxmonitor

**Comment by NorthV** [comment]
That would be great.

**Comment by macbre** [comment]
@NorthV - https://tools.sphinxsearch.com/ seems to be down. Closing this ticket.
