### ISSUE TITLE
Unable to start crond

### ISSUE THREAD

**Issue by jseverinson** [macbre/docker-sphinxsearch#11]
Hi, let me first say thanks for this docker image and apologise in advance if this is a noob question, I'm learning as I go. 😊

I've set up this image and got Sphinx to a point where I'm very happy with it, but I'm struggling to get a cronjob set up to periodically re-index. crond seems not to be running and as I try to launch it I get this:

```
node86411-webb30-search1:~# /etc/init.d/crond start
 * Starting busybox syslog ...
/sbin/syslogd: unrecognized option: Z
BusyBox v1.31.1 () multi-call binary.

Usage: syslogd [OPTIONS]

System logging utility

-nRun in foreground
-R HOST[:PORT]Log to HOST:PORT (default PORT:514)
-LLog locally and via network (default is network only if -R)
-C[size_kb]Log to shared mem buffer (use logread to read it)
-KLog to kernel printk buffer (use dmesg to read it)
-O FILELog to FILE (default: /var/log/messages, stdout if -)
-s SIZEMax size (KB) before rotation (default 200KB, 0=off)
-b NN rotated logs to keep (default 1, max 99, 0=purge)
-l NLog only messages more urgent than prio N (1-8)
-SSmaller output
-tStrip client-generated timestamps
-DDrop duplicates
-f FILEUse FILE as config (default:/etc/syslog.conf)
 * start-stop-daemon: failed to start `/sbin/syslogd'
 * Failed to start busybox syslog [ !! ]
 * ERROR: syslog failed to start
 * ERROR: cannot start crond as syslog would not start
```

Making it a bit more verbose with the -d option I see this:

```
+ ebegin 'Starting busybox syslog'
 * Starting busybox syslog ...
+ yesno 
+ '[' -z  ]
+ return 1
+ yesno 
+ '[' -z  ]
+ return 1
+ '[' -n  ]
+ '[' -n  ]
+ eval start-stop-daemon --start --exec /sbin/syslogd --pidfile /var/run/syslogd.pid -g wheel -k 027 -- -Z
+ start-stop-daemon --start --exec /sbin/syslogd --pidfile /var/run/syslogd.pid -g wheel -k 027 -- -Z
/sbin/syslogd: unrecognized option: Z
BusyBox v1.31.1 () multi-call binary.

Usage: syslogd [OPTIONS]

System logging utility

-nRun in foreground
-R HOST[:PORT]Log to HOST:PORT (default PORT:514)
-LLog locally and via network (default is network only if -R)
-C[size_kb]Log to shared mem buffer (use logread to read it)
-KLog to kernel printk buffer (use dmesg to read it)
-O FILELog to FILE (default: /var/log/messages, stdout if -)
-s SIZEMax size (KB) before rotation (default 200KB, 0=off)
-b NN rotated logs to keep (default 1, max 99, 0=purge)
-l NLog only messages more urgent than prio N (1-8)
-SSmaller output
-tStrip client-generated timestamps
-DDrop duplicates
-f FILEUse FILE as config (default:/etc/syslog.conf)
 * start-stop-daemon: failed to start `/sbin/syslogd'
+ eend 1 'Failed to start busybox syslog'
 * Failed to start busybox syslog [ !! ]
+ yesno 
+ '[' -z  ]
+ return 1
+ return 1
+ exit 1
 * ERROR: syslog failed to start
 * ERROR: cannot start crond as syslog would not start
```

The `start-stop-daemon --start --exec /bin/syslogd` seems to have a redundant option with it, and if I remove that I can start syslogd, but then crond will say syslogd is already running and still complain it cannot be started.

Any advice on what to do here? Thanks!

**Comment by jseverinson** [comment]
I believe I found the issue. This was [a bug in Alpine Linux](https://gitlab.alpinelinux.org/alpine/aports/-/issues/9986). It can be fixed by replicating [this commit](https://gitlab.alpinelinux.org/alpine/aports/-/commit/1e0a736522e5301941563c0c1ab623626a6fedad), by editing `/etc/conf.d/syslog` and change the "-Z" to "-t".

Leaving this open as it might make sense to patch the image or upgrade the Alpine Linux version. I imagine more people will want to have crond running for their Sphinx container. Thanks!

**Comment by macbre** [comment]
@jseverinson - do you want to run `syslog` daemon inside Sphinx Docker container? Or am I getting this wrong?

**Comment by jseverinson** [comment]
Hi Maciej! Not really, I want to run crond inside it to reindex the Sphinx
index, but crond won’t start because of this error in how syslogd is
called. 😊

lör 31 okt. 2020 kl. 19:55 skrev Maciej Brencz <notifications@github.com>:

**Comment by macbre** [comment]
You should rather [use cron running on the host machine](https://devops.stackexchange.com/questions/447/why-it-is-recommended-to-run-only-one-process-in-a-container) (not inside the Docker container) and run `docker exec sphinx <reindex command>`:

```
docker exec -i sphinx_container indexer --rotate --print-queries --all
docker kill --signal=HUP sphinx_container  # this one will make the Sphinx daemon reload the index files
```

Best :slightly_smiling_face:

**Comment by jseverinson** [comment]
Hi again Maciej. This might be me being entirely incompetent, but I'm using
the Jelastic virtualisation platform which means a virtual machine is built
from a Docker container. As such I don't have access to any host machine.
😊 In any case, I solved this for my own sake, just figured this change
might be something you'd want to introduce in future versions.

All the best,
John

**Comment by macbre** [comment]
@jseverinson - sure :slightly_smiling_face:  Are you using `macbre/sphinxsearch` image "directly" or did you create your own `Dockerfile` that uses it?

I'm asking because `alpine:3.12` base image does not seem to have `syslog.conf` file...
