### ISSUE TITLE
CMD command failed inside Dockerfile

### ISSUE THREAD

**Issue by thewind1984** [macbre/docker-sphinxsearch#16]
Hello @macbre ,

regarding the latest PR you merged in, the last line

`CMD searchd --nodetach --config ${CONF_FILE}`

does not work. It fails with the error

`FATAL: malformed or unknown option near '--config'; use '-h' or '--help' to see available options.`

I suppose here could be different cases to fix it
* `CMD searchd --nodetach --config "${CONF_FILE}"`
* `CMD ["searchd", "--nodetach", "--config", "${CONF_FILE}"]`

need to be checked ASAP...

**Comment by macbre** [comment]
Let's first revert #15 and implement a proper CI in this repository.

**Comment by macbre** [comment]
@thewind1984 - feel free to proceed as we now have #19 🙂

**Comment by macbre** [comment]
Resolved by #20
