### ISSUE TITLE
Update to version 3.2.1

### ISSUE THREAD

**Issue by glukkkk** [macbre/docker-sphinxsearch#6]
Update to version 3.2.1, please

**Comment by macbre** [comment]
A note for myself: use http://sphinxsearch.com/files/sphinx-3.2.1-f152e0b-linux-amd64-musl.tar.gz

**Comment by glukkkk** [comment]
:+1:

**Comment by macbre** [comment]
@glukkkk - https://hub.docker.com/r/macbre/sphinxsearch - here you are :)
